### ISSUE TITLE
Tracking events

### ISSUE THREAD

**Issue by hgezim** [pennersr/django-trackstats#13]
My goal is to record user events and then be able to answer questions like: which user has visited the pricing page the most, how many times did they visit it in a week, in a month?
So, the event I'm interested in tracking might be "visited pricing page".

Would I have to create my own `Events` model with `user`,`action`,`date` then call `StatisticByDate.objects.record` or can I log activity/events some other way?

**Comment by pennersr** [comment]
There is a StatisticByDateAndObject model that you can use for this. In your case, the object points to the pricing page if that is a Django model).

**Comment by hgezim** [comment]
What throws me off is the `period` argument for my use case.

Say in my `get` method of the view I have this:

```
def get(request):
    StatisticByDateAndObject.objects.record(
            period=Period.DAY,
            metric=Metric.objects.VIEW_PAGE,
            value=1,
            object=request.user,
            date=datetime.now())
```

It's not clear why I'd need `period` at all. Since I have the date, period comes in only when I want to report on it not track. For each time this view is rendered, I just want to increment my count and then later on choose to report on weeks, months, etc.

**Comment by pennersr** [comment]
Your use case seems to be storing events. This is a bit of a misfit for this package, which is more targetting at storing statistics per date in a denormalized (hence the period) fashion.
