### ISSUE TITLE
Why unique on date?

### ISSUE THREAD

**Issue by george-silva** [pennersr/django-trackstats#7]
I'm monkeypatching the library to have hour statistics. Why make it unique?

I mean, let's just convert this into a datetimefield and allow devs to track stuff with hour or minute resolution?

**Comment by pennersr** [comment]
If you turn it into a DateTimeField, chances are likely you will end up with invalid data, like "2018-04-22 16:37.23". I would prefer to store hourly statistics as a combination of a DateField and a PositiveIntegerField for the hours.
